services:

  postgres:
    image: postgres:16
    container_name: aqua_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aquaxai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aquaxai"]
      interval: 5s
      timeout: 5s
      retries: 10


  ollama:
    image: ollama/ollama:latest
    container_name: aqua_ollama
    restart: unless-stopped

    ports:
      - "11434:11434"

    volumes:
      - ollama_storage:/root/.ollama


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: aqua_backend
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/aquaxai
      OLLAMA_HOST: http://ollama:11434

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./backend/app/ml/models:/app/app/ml/models
      - ./dataset:/app/dataset

    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: aqua_frontend
    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend


volumes:
  postgres_data:
  ollama_storage: